### ISSUE TITLE
Bigger differences between (Large) Transport and Trains

### ISSUE THREAD

**Issue by erikroe** [Freelancer-Sirius-Revival/FLSR#10]
Currently Transports and Trains are merely a progression from lowest to highest tier transport ships. To give a better distinction between them we may want to do this:
- Make trains more armored (150k instead of 100k)
- Add more weapon power capacity on trains
- Change engines of Transports to almost ignore whatever is loaded
- Change engines of Transports to be faster (100m/s)

The general steering of each of those ships according to its size should be adjusted, too.

**Comment by FireFlyEx** [comment]
You can't change their speed because then their escorts couldn't keep up. It also wouldn't make sense since they are basically space barges and being slow is part of it. I can apply my steering system to give each a tiered steering.

Suggestions:

Give them a tiered power core with limits on which ship can mount what, so weapons are more effective on the higher end.

Give trains an extra equipment slot where they could mount several optional items (not lootable):

- Defensive Field (Shield) with a high enough power usage that they can't shoot and have a shield at the same time. Maybe, should also be high enough that the power draw from starting cruise would drop the shield? (may not be possible because of energy drain priority?) Follows the shield type vs weapon type system.

- Secondary Power Core so you can fire weapons for longer or mount higher energy drain weapons that are more deadly.

- Ablative Armor which gives you up to a 25% hull damage resistance.

- Storage Booster which gives up up to 20% more storage. (possible...? probably not?)

- Cruise Booster which lowers cruise charge time by up to 2 seconds (possible...? probably not?)

Give transports an extra slot with several options:

- Missile Turret but with limits on maximum weapon level so that people will still consider getting a Train.

- Energy Disruptor that is a cruise disruptor but also does high energy damage and uses a lot of energy.

- Fuel Enhancer (Thruster) that increases speed to 100 with energy draw that will make it last up to 10 seconds.

**Comment by erikroe** [comment]
Shields are by lore not working for bigger ships due technical limitations. We want to keep it so.
Longer firing weapons on any transports is not really useful because their defense is generally quite shitty, and that's just correct so against any stronger enemy.
The armour thing may come for any ship at some point.
The storage booster is currently impossible and may also not make any sense here unless we make it look right for the ship visually.
Cruise booster only works by giving it different engines.
Missile turrets for those ships actually should be for all those ships I think.
I don't know what an energy disruptor would be benefitting a transport for?
Transports have no thrusters.

**Comment by FireFlyEx** [comment]
Cruise disruptor pointed to the rear to prevent ships from cruising after you? If you get scanned and run for it you could lose some pursuers. Just a thought.

**Comment by erikroe** [comment]
That's a good point, yeah
