### ISSUE TITLE
Check Freeport shipdealer rooms and icons

### ISSUE THREAD

**Issue by erikroe** [Freelancer-Sirius-Revival/FLSR#15]
Some Freeports have rooms where the link to the shipdealers are not done properly.

**Comment by FireFlyEx** [comment]
So far this is all I have found:

BW01_02_Bar.ini - Missing IDS_HOTSPOT_SHIPDEALER_ROOM block
BW01_02_Shipdealer - Missing PlayerShipPlacement block and ForSaleShipPlacement block was pointed to the wrong setpoint (X/Shipcentre/01 instead of X/Shipcentre/02).
* It throws an error saying that X/Shipcentre/02 could not be found in the room .ini file. It throws an error because the THN file (br_04_Deck_ambi_int_01.thn) defines it.

The br_04_Deck_ambi_int_01.thn >> X/Shipcentre/02 issue also shows up in BR05_01_Deck2.ini.

I have tested all of the Freeport bases in game and haven't noticed anything crashing or not functioning normally. Is this issue still an issue?

**Comment by erikroe** [comment]
Yes it's still an issue. Feel free to take up to fix it ;) Would be great!
