### ISSUE TITLE
Large Ship Physics Update

### ISSUE THREAD

**Issue by FireFlyEx** [Freelancer-Sirius-Revival/FLSR#410]
In Vanilla the only playable ships were fighters and freighters. Obviously, FLSR allows you to fly everything, so new physics have to be applied to all of these previously unflyable ships.

I have made a spreadsheet that allows me to calculate working physics for all sizes of ships. So my goal here is to make all of these ships feel good to fly and hopefully do not break anything like auto-pilot.

Known issues:
- Large ships spin when hit by smaller ships. **Not solvable to my knowledge.**
- Large ships have issues docking with moors on various bases. **This is solvable by changing the location of HpDockMountX/HpDockPointX hardpoints in dockable solar CMP files.**
- Large ships do not work well in ship formations. **Can be fixed by editing existing formations to leave more room for a player ship.**

I will be submitting fixed dockable solars in a separate Issue/PR.

**Comment by erikroe** [comment]
The spinning can be solved by FLHook itself. There is already stuff out there that we have (partially?) implemented.

The docking on stations is mostly on shipyards, and the issue is the autopilot trying to evade the shipyard structures I think. I'll be wanting to reset that some time later. There's already an issue for it.

Formations need to be revisited, yes.
