### ISSUE TITLE
Holes in LI Battleship at distance

### ISSUE THREAD

**Issue by erikroe** [Freelancer-Sirius-Revival/FLSR#439]
![grafik](https://user-images.githubusercontent.com/48999656/224178268-b3e073ab-1759-4a49-86cd-82053312f547.png)
It seems with longer distance a texture or mesh is missing. Probably the Osiris specific LOD texture and Mat that I have possibly overriden with the last update of li_capships.mat

**Comment by thaddeus-ex** [comment]
this is caused by the "osiris_lod" texture not present in li_capships.mat. requires either the texture to be added to li_caps.mat or referencing the or_ships.mat in shiparch entry:

material_library = ships\liberty\li_capships.mat
material_library = ships\order\or_ships.mat
material_library = fx\envmapbasic.mat
etc

suggest the above for the moment as a quick fix as I want to make a proper li_battleship_lod texture for this ship, as the brown order texture does show itself even at 1300m

**Comment by thaddeus-ex** [comment]
and the solar model more importantly

**Comment by erikroe** [comment]
Fixed it by adding it to the li capship mat for now.
