### ISSUE TITLE
Finish the trade rings in the Hokkaido system.

### ISSUE THREAD

**Issue by MaikMaikov** [Freelancer-Sirius-Revival/FLSR#542]
Since we're talking about the impact of history after the events of vanilla, Hokkaido should get some long-awaited trade lines and infrastructure development in the system.

**Comment by thaddeus-ex** [comment]
Its certainly possible. The under construction tradelane in Hokkaido is not one piece though, it follows a two part dog-leg with the lane change slap in the middle of the Kyufu Gap - a high radiation area. It also has the problem (in lore) that it isnt that useful as the Chugoku gate will never be completed. Gas miners while working in the area have a short run to the gate anyway.

If we write some lore that says that the zone (at least around the convergence point - not the whole field) is now low radiation (so that the investment wont rot before our proverbial eyes) and that the nexus zone (of the two tradelanes) was purposed for another more wortwhile transit gate, say, to Tohoku then we might have something. You could say that the Samura/Kishiro are dismantling the unfinshed Chugoku gate for research purposes (maybe...) justifying a 2nd completed tradelane. Very little else north of the gap to justify investment at that level, new gas field maybe? 

![2023-03-29 (2)](https://user-images.githubusercontent.com/92892138/228485711-ffec14d2-b4b3-47f2-9817-973082e6701d.png)

Someone might have already done something similar

**Comment by MaikMaikov** [comment]
Can you get information from the lore as to why the gate to Chugoku will not be completed?

**Comment by thaddeus-ex** [comment]
H 132984
	We see the Hokkaido campaign as a thinly veiled attempt by Samura to
	force the taxpayers of Kusari to pay for their access to new H-Fuel
	fields in the Crow Nebula in the name of fighting the threat of the
	Blood Dragons. The government has no intention of ever completing the
	Chugoku Gate. They will abandon it within the next few years,
	declaring victory over the evil terrorists.

H 132995
	As far as we're concerned, they should stop the Chugoku Gate project
	as soon as possible, as it is a colossal waste of money that only
	aggravates the Blood Dragon problem. The Blood Dragons are an
	annoyance, but they have served their purpose well. Once the fields in
	Hokkaido are fully operational, Samura will have a revelation and
	rethink its views towards the terrorists.

H 133344
	Samura thinks that once that the government pulls back from the
	Chugoku Gate project that Hokkaido will finally be theirs. They are
	gravely mistaken. The GMG will insure that the Blood Dragons live on,
	and do not rest in peace until Samura abandons Hokkaido. The victory
	will be sweet.

H 133375
	Samura has accomplished our primary goal of establishing a viable gas
	field in Hokkaido. The government's assistance was invaluable
	achieving this goal. We no longer need the Chugoku Gate project to
	justify our presence in Hokkaido.

This isnt even half of the infocards on the Chugoku gate, it is seen as in un-popular waste of money by most people in Kusari. It does confirm that Samura wants to continue and build on its presence in Hokkaido, expanding their gasmining ventures there.

**Comment by erikroe** [comment]
I agree with Thaddeus. It's a good idea initially to see those TLRs completed, but lore-wise there's absolutely no intention of Kusari to ever do that. So I'll close this issue until the day we revisit the lore of FLSR – but then I still think this will not be implemented.
