### ISSUE TITLE
Rendering of Textures all wrong on Windows

### ISSUE THREAD

**Issue by erikroe** [Freelancer-Sirius-Revival/FLSR#663]
For some odd reason Caenen and Sarge both have completely not working illumination maps and also very badly blurry textures of planets. Also Planetary Rings are not rendered, too. Both use Nvidia and Windows 10.
As it should be:
![grafik](https://github.com/Freelancer-Sirius-Revival/FLSR/assets/48999656/9718943f-4005-4216-afbb-b165878bad67)

As it looks for them:
![grafik](https://github.com/Freelancer-Sirius-Revival/FLSR/assets/48999656/38b023b9-844a-470e-8609-dd00f736fe21)
![grafik](https://github.com/Freelancer-Sirius-Revival/FLSR/assets/48999656/a8d49c7d-7f3d-44bf-bac7-6c3fe0e3c3e8)

@BC46 Do you have any clue what this may be? Any such reports that happened on FL HDE already? Since there have been many people already there with most different systems and bugs.

**Comment by BC46** [comment]
If there are only one or two maps that aren't showing properly, it'd have to be a bug in one of the mat or texture files. However, since you say that the detail and emission maps aren't working at all, I suspect this is the same issue I've observed when watching some HDE v0.5 streams back in the day. Long story short, the problem is caused by the following combination: NVIDIA GPU + Anisotropic Filtering + d3d8to9. You guys use d3d8to9 for your DirectX hook, right?

When you select DxWrapper as the Graphics API in the HDE installer, there'll be an explicit warning about the issue, since DxWrapper uses d3d8to9 under the hood: 
![image](https://github.com/Freelancer-Sirius-Revival/FLSR/assets/45081813/f679bb9e-10d1-48e7-8647-3ace35e623a9)

You can confirm this is the same problem by asking Sarge or Caenen to inspect the planet again after temporarily renaming the `d3d8.dll` file, or disabling AF. Though I must say I didn't know that forcing AF through DirectX 8 would also trigger this bug.

I did touch on the problem briefly during a discussion regarding DxWrapper: https://github.com/elishacloud/dxwrapper/issues/134#issuecomment-1460401679. The issue has since been fixed in the latest HEAD snapshots of DxWrapper on GitHub (not the release build because that one is a bit old). 

In order to make the least possible sacrifices when resolving the problem, your best bet would probably be to update your DirectX hook so it uses DxWrapper instead of d3d8to9. However, I don't have access to your DirectX hook's source code, so unfortunately I can't help you with this.

**Comment by erikroe** [comment]
Thanks for all that, this is super helpful! I'll check with the others about it.

**Comment by Caenen** [comment]
![grafik](https://github.com/Freelancer-Sirius-Revival/FLSR/assets/79576409/1affc4b2-a3e5-4329-b92e-5a1a8baf3551)
I can confirm this workaround works.

**Comment by erikroe** [comment]
Gave it to Caenen to test and so far it all looks good. I'll replace our d3d8 with the given DxWrapper also enabling anti aliasing, too.
