### ISSUE TITLE
Empathy rate Ageira - Bounty Hunters Guild Wrong

### ISSUE THREAD

**Issue by thaddeus-ex** [Freelancer-Sirius-Revival/FLSR#697]
Empathy rate Agiera - BHG set to high

[RepChangeEffects]
group = co_vr_grp
...
...
empathy_rate = gd_bh_grp, 0.5
...

rep change is far to sigificant even for an affiliate, resulting in a negative rep in short order, probably due to misplaced decimal point
suggest
empathy_rate = gd_bh_grp, 0.05

**Comment by erikroe** [comment]
I agree this is a too high value. The idea was to say that shot-down corporation ships are instantly getting the Bounty Hunters on your tail. I however changed it now to be 0.2 instead of 0.5. Meaning there's almost 3 times more Corp ships to destroy before you get the Bounty Hunters very angry at you.
