### ISSUE TITLE
Rebalance Capship Missiles

### ISSUE THREAD

**Issue by erikroe** [Freelancer-Sirius-Revival/FLSR#701]
Currently missile launchers of capships all have different values. Those should be uniform among them.

**Comment by Caenen** [comment]
I'd like to quickly reimplement the rebalancing based on the following approach:

* Li Missile: keep damage 4000, launcher refire delay 1.0 -> 2.0
** potential DPS becomes 2000 per L mount, instead of 4000. Damage capacity until ammo dry stays 4000*200 = 800000

* Br Missile: damage increased to 5000, keep refire delay 2.0
** DPS becomes 2500 per L mount, instead of 1500. Damage capacity is 750000

* Ku Missile: damage decreased to 2500, refire delay stays 1.0. Ammo capacity increased to 300.
** DPS becomes 2500 per L, instead of 3500. Damage capacity is 750000

* RH missile: damage stays the same, refire delay down 2.0 -> 1.0.
** DPS becomes 2000 per L, instead of 1000, damage capacity is 800000

This keeps the different houses' launchers somewhat distinct but now equal in power level. Follow up can be done if needed later.
