### ISSUE TITLE
Remove missile ammo from Capships

### ISSUE THREAD

**Issue by erikroe** [Freelancer-Sirius-Revival/FLSR#785]
Remove missile ammo from Capships; they usually have more than enough cargo space and any loaded ammo has literally no additional game-play reason to exist.

**Comment by Caenen** [comment]
After some more observations of the live state of capship missiles, I implemented this alongside some balance changes:

Missiles currently become very "spammy" when used by capital ships, giving fighter players no room to act while the enemy keeps launching them if their countermeasure dropper empties (which is does very quickly against them). They also "linger" a long time as capships other than gunboats fly so slow that their travel times become insane (missiles carry over the parents' speed when launching, before adding their own acceleration). This combined badly with Freelancer's targeting cursor looking for the nearest possible target, which missiles other than your own will constantly distract.

Consequentially, all capship missiles get long refire delays (4.5 to 6 seconds), and deal the same hit damage each (4000). The difference in refire time is proportional to the normal DPS of the L turret of the house. Their travel speed is increased and lifetime decreased, keeping to the previous seeker range and travel range scheme, to make their impacts more reliable and avoid long "you are constantly being chased by a missile" moments for fighters.

I also gave missile launchers and CD launchers the ability to fire regardless of facing direction. Damage missiles already have 360° total field of view, and testing confirms that this works out nicely for them.

Since capship missiles no longer require ammunition, I removed the NPC-specific copies of them as those were used to give them no ammo consumption, and nothing else (which also prevented them from being lootable from NPCs, though this does not matter for this capital equipment much).
