### ISSUE TITLE
Concept for Company factions

### ISSUE THREAD

**Issue by erikroe** [Freelancer-Sirius-Revival/FLSR#87]
Company factions currently serve almost no useful purpose at all.

**Comment by FireFlyEx** [comment]
Is it possible to make some goods require rep to buy? For some reason I never thought to try that. At some point we should make that list of companies and what they make so we can make sure they are the only ones selling it. Also.. we should adjust company alliances with state militaries and police forces so that it's more possible to have to increase rep with specific companies to get stuff. Maybe even make some rivalries between house companies instead of one big happy family. For example, house militaries probably shouldn't have any connection to companies. And maybe getting good with say BMM makes your rep to Bowex go down a little (just an example).
